#!/bin/sh
#
# prepare-travis-ci: Make a fresh repo buildable in CI
#

if [ -d ./build-aux ] ; then
    : ;
else
    echo "$0: I expect to be run in project root"
    exit 255
fi

if [ "x$1" = "xbootstrap" ] ; then
    shift
    echo "Bootstrap -- installing GNU tool chain"
    sudo apt-get install automake autoconf check
fi

if [ "x$TRAVIS" = "xtrue" ] ; then
    echo "Checking versions..."
    autoconf --version | head -1
    automake --version | head -1

    echo "Setting up GNU autotools..."
    export CFLAGS="$CFLAGS -DDEBUG"
    ./build-aux/autogen.sh "$@"

elif [ -f config.status ] ; then
    echo "Not running under CI. Will run but not force autoreconf."
    autoreconf -vi
    ./configure "$@"

elif [ -f configure ] ; then
    echo "Running configure..."
    ./configure "$@"
fi

echo "Ready. Run make now."
