#!/bin/sh
#
# prepare-travis-ci: Make a fresh repo buildable in CI
#

echo "Installing missing automake utilities..."
automake --add-missing

if [ "x$TRAVIS" = "xtrue" ] ; then
    echo "Checking versions..."
    autoconf --version | head -1
    automake --version | head -1

    echo "Running autoreconf to generate required build files"
    export CFLAGS="$CFLAGS -DDEBUG"
    autoreconf -fi

elif [ -f config.status ] ; then
    echo "Not running under CI. Will not force autoreconf."
    autoreconf -vim

else
    echo "Config.status is missing. Will bootstrap."
    autoconf 
    ./configure && make
fi
