#!/bin/sh
#
# prepare-travis-ci: Make a fresh repo buildable in CI
#

if [ "x$TRAVIS" = "xtrue" ] ; then
    echo "Installing test dependencies..."
    cpanm -nq Test::Command

    echo "Checking versions..."
    autoconf --version | head -1
    automake --version | head -1

    echo "Running autoreconf to generate required build files"
    autoreconf -fi

else
    echo "Not running under CI. Will not force autoreconf."
    autoreconf -vim
fi
